avito_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: szvttdq-bs56030
      user: AIRBYTE_USER
      password: 2025@2025
      role: AIRBYTE_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: AIRBYTE_SCHEMA
      threads: 4
      client_session_keep_alive: false