version: 2

sources:
  - name: AIRBYTE_DATABASE
    description: 'Avito car data brut '
    schema: AIRBYTE_SCHEMA
    database: AIRBYTE_DATABASE
    tables:
      - name: AVITOCARDATASET
    
    
    
